version: '3'
services:
  mysql:
    image: mysql:5
    restart: always
    networks:
      - redmine
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
  memcached:
    image: memcached:alpine
    restart: always
    networks:
      - redmine
    ports:
      - 11211:11211
  redmine:
    image: sameersbn/redmine
    restart: always
    depends_on:
      - mysql
      - memcached
    networks:
      - redmine
    ports:
      - 8088:80
    environment:
      - TZ=Asia/Tokyo
      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=redmine
      - DB_NAME=redmine
      - MEMCACHE_HOST=memcached
      - MEMCACHE_PORT=11211
      - NGINX_WORKERS=1024
networks:
  redmine:
