version: '3'
services:
  mysql:
    image: mysql:5
    restart: always
    networks:
      - redmine
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  memcached:
    image: memcached:alpine
    restart: always
    networks:
      - redmine
    ports:
      - 11211:11211
  redmine:
    image: redmine:passenger
    restart: always
    depends_on:
      - mysql
      - memcached
    networks:
      - redmine
    ports:
      - 8088:3000
    environment:
      - TZ=Asia/Tokyo
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
      - REDMINE_DB_ENCODING=utf8mb4
    # volumes:
    #   - ./files:/usr/src/redmine/files
    #   - ./log:/usr/src/redmine/log
    #   - ./plugins:/usr/src/redmine/plugins
    #   - ./themes:/usr/src/redmine/public/themes
networks:
  redmine:
