version: '3'
services:
  mysql:
    image: mysql:5
    container_name: redmine_mysql
    restart: always
    networks:
      - redmine
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=redmine
    volumes:
      - ./mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  memcached:
    image: memcached:alpine
    container_name: redmine_memcached
    restart: always
    networks:
      - redmine
  redmine:
    image: redmine:passenger
    container_name: redmine
    restart: always
    depends_on:
      - mysql
      - memcached
    networks:
      - redmine
    ports:
      - 8088:3000
    environment:
      - TZ=Asia/Tokyo
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_PORT=3306
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=redmine
      - REDMINE_DB_ENCODING=utf8mb4
      - NO_PROXY=${NO_PROXY}
      - FTP_PROXY=${FTP_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    volumes:
      - ./files:/usr/src/redmine/files
      - ./log:/usr/src/redmine/log
      - ./plugins:/usr/src/redmine/plugins
      - ./themes:/usr/src/redmine/public/themes
networks:
  redmine:
